openapi: "3.2.0"
info:
  version: "0.0.1"
  title: "study helper"
  description: "API for the study helper"

tags:
  - name: Authentication
  - name: Category
  - name: Tag
  - name: Task

paths:
  /auth/login:
    post:
      operationId: "login"
      description: "Get authentication token"
      tags:
        - Authentication
      requestBody:
        description: "Login credentials for logging in"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Auth"
      responses:
        "200":
          description: "Successfully logged in"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthSuccess"
        "401":
          description: "Unauthorised"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /auth/signup:
    post:
      operationId: "signup"
      description: "Sign up and get authentication token"
      tags:
        - Authentication
      requestBody:
        required: true
        description: "Login credentials for signing up"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Auth"
      responses:
        "200":
          description: "Successfully signed up"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AuthSuccess"
        "401":
          description: "Unauthorised"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"


  /categories:
    get:
      operationId: "getCategory"
      description: "Fetch all categories"
      tags:
        - Category
      responses:
        "200":
          description: "Categories fetched"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Category"
        "400":
          description: "Bad request"
        "401":
          description: "Unauthorised"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
        default:
          description: "Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - BearerAuth: []
    post:
      operationId: "addCategory"
      description: "Add categories"
      tags:
        - Category
      requestBody:
        required: true
        description: "Categories"
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Category"
      responses:
        "200":
          description: "Category added"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Category"
        "400":
          description: "Bad request"
        "401":
          description: "Unauthorised"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
        default:
          description: "Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - BearerAuth: []

  /categories/{id}:
    get:
      operationId: "getCategory"
      description: "Fetch a Category"
      tags:
        - Category
      parameters:
        - in: path
          description: "ID of Category"
          name: "id"
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "Category fetched"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Category"
        "400":
          description: "Bad request"
        "401":
          description: "Unauthorised"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
        default:
          description: "Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - BearerAuth: []
    put:
      operationId: "updateCategory"
      description: "Edit a category"
      tags:
        - Category
      parameters:
        - in: path
          description: "ID of Category"
          name: "id"
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        description: "Data for editing category"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Category"
      responses:
        "200":
          description: "Category edited"
        "400":
          description: "Bad request"
        "401":
          description: "Unauthorised"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
        default:
          description: "Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - BearerAuth: []
    delete:
      operationId: "deleteCategory"
      description: "Delete a category"
      tags:
        - Category
      parameters:
        - in: path
          description: "ID of Category"
          name: "id"
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: "Category deleted"
        "400":
          description: "Bad request"
        "401":
          description: "Unauthorised"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
        default:
          description: "Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - BearerAuth: []


  /tags:
    get:
      operationId: "getTags"
      description: "Fetch all tags"
      tags:
        - Tag
      responses:
        "200":
          description: "Tags fetched"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Tag"
        "400":
          description: "Bad request"
        "401":
          description: "Unauthorised"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
        default:
          description: "Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - BearerAuth: []
    post:
      operationId: "addTags"
      description: "Add tags"
      tags:
        - Tag
      requestBody:
        required: true
        description: "Tags"
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: "#/components/schemas/Tag"
      responses:
        "200":
          description: "Tags added"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Tag"
        "400":
          description: "Bad request"
        "401":
          description: "Unauthorised"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
        default:
          description: "Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - BearerAuth: []

  /tags/{id}:
    get:
      operationId: "getTag"
      description: "Fetch a tag"
      tags:
        - Tag
      parameters:
        - in: path
          description: "ID of tag"
          name: "id"
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "Tag fetched"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tag"
        "400":
          description: "Bad request"
        "401":
          description: "Unauthorised"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
        default:
          description: "Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - BearerAuth: []
    put:
      operationId: "updateTag"
      description: "Edit a tag"
      tags:
        - Tag
      parameters:
        - in: path
          description: "ID of tag"
          name: "id"
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        description: "Data for editing tag"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Tag"
      responses:
        "200":
          description: "Tag edited"
        "400":
          description: "Bad request"
        "401":
          description: "Unauthorised"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
        default:
          description: "Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - BearerAuth: []
    delete:
      operationId: "deleteTag"
      description: "Delete a tag"
      tags:
        - Tag
      parameters:
        - in: path
          description: "ID of tag"
          name: "id"
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: "Tag deleted"
        "400":
          description: "Bad request"
        "401":
          description: "Unauthorised"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
        default:
          description: "Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - BearerAuth: []


  /task/{id}:
    get:
      operationId: "getTask"
      description: "Fetch a task"
      tags:
        - Task
      parameters:
        - in: path
          description: "Task ID for fetching task"
          name: "id"
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: "Task fetched"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "400":
          description: "Bad request"
        "401":
          description: "Unauthorised"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
        default:
          description: "Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - BearerAuth: []
    post:
      operationId: "addTask"
      description: "Add a task to /categories/{id}"
      tags:
        - Task
      parameters:
        - in: path
          description: "Box ID for creating task"
          name: "id"
          required: true
          schema:
            type: integer
      requestBody:
        description: "Data for creating task"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
      responses:
        "200":
          description: "Task added"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "400":
          description: "Bad request"
        "401":
          description: "Unauthorised"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
        default:
          description: "Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - BearerAuth: []
    put:
      operationId: "updateTask"
      description: "Edit a task"
      tags:
        - Task
      parameters:
        - in: path
          description: "Task ID for editing task"
          name: "id"
          required: true
          schema:
            type: integer
      requestBody:
        description: "Data for editing task"
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Task"
      responses:
        "200":
          description: "Task edited"
        "400":
          description: "Bad request"
        "401":
          description: "Unauthorised"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
        default:
          description: "Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - BearerAuth: []
    delete:
      operationId: "deleteTask"
      description: "Delete a task"
      tags:
        - Task
      parameters:
        - in: path
          description: "Task ID for deleting task"
          name: "id"
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: "Task deleted"
        "400":
          description: "Bad request"
        "401":
          description: "Unauthorised"
        "403":
          description: "Forbidden"
        "404":
          description: "Not Found"
        default:
          description: "Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      security:
        - BearerAuth: []

components:
  securitySchemes:
    BearerAuth:
      description: "Security schema for JWT authentication"
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    Category:
      description: "Category Schema"
      properties:
        id:
          type: integer
          readOnly: true
          examples:
            - 2
        name:
          type: string
          examples:
            - "CS 61A"

    Tag:
      description: "Tag Schema"
      properties:
        id:
          type: integer
          readOnly: true
          examples:
            - 1
        name:
          type: string
          examples:
            - "Computer Science"

    Task:
      description: "Task schema"
      properties:
        id:
          type: integer
          readOnly: true
          examples:
            - 3
        name:
          type: string
          examples:
            - "Understand using procedures as arguments"
        content:
          type: string
          examples:
            - "blah blah"
        category:
          type: integer
          examples:
            - 2
        tags:
          type: array
          items:
            type: integer
          uniqueItems: true
          examples:
            - [1, 2]
        frequency:
          type: integer
          description: "Frequency of task in days, 0 is for archived tasks"
          examples:
            - "1"

    Frequency:
      description: "Frequency schema"
      type: array
      items:
        type: integer
      uniqueItems: true
      examples:
        - [1, 2, 7, 14, 28]

    Account:
      description: "Account schema"
      properties:
        username:
          type: string
          examples:
            - "AzureDiamond"
        email:
          type: string
          examples:
            - "azurediamond@example.com"
        password:
          type: string
          writeOnly: true
          examples:
            - "hunter2"

    Auth:
      description: "Authentication schema"
      properties:
        username:
          type: string
          examples:
            - "AzureDiamond"
        password:
          type: string
          examples:
            - "hunter2"
      required:
        - username
        - password

    AuthSuccess:
      description: "Authentication schema for successful responses"
      properties:
        token:
          type: string
          readOnly: true
          examples:
            - "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IkF6dXJlRGlhbW9uZCIsImlhdCI6MTUxNjIzOTAyMn0.96tkfxJnBWnf4Lt6T1cYshqjp4q_aIlwV1D3D0Dk1LU"

    Error:
      description: "Error schema"
      properties:
        error:
          type: string
          examples:
            - "error"
      required:
        - error
